- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-pypy-jobs-nonvoting
      - lib-forward-testing
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-swift-dsvm-functional
        - legacy-swift-dsvm-functional-identity-v3-only:
            voting: false
        - legacy-swiftclient-dsvm-functional
        - legacy-swiftclient-dsvm-functional-identity-v3-only:
            voting: false
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-swift-dsvm-functional
        - legacy-swiftclient-dsvm-functional
    post:
      jobs:
        - openstack-tox-cover
