- job:
    name: swiftclient-functional
    description: |
      Legacy swiftclient funcional jobs for Ocata only.
    parent: legacy-dsvm-base
    run: playbooks/swiftclient-dsvm-functional/run.yaml
    post-run: playbooks/swiftclient-dsvm-functional/post.yaml
    timeout: 6000
    required-projects:
      - openstack/devstack-gate
      - openstack/python-swiftclient
      - openstack/swift

- job:
    name: swiftclient-functional-identity-v3-only
    parent: legacy-dsvm-base
    description: |
      Legacy swiftclient funcional jobs for Ocata only.

      This uses Identity API v3.
    run: playbooks/swiftclient-dsvm-functional-identity-v3-only/run.yaml
    post-run: playbooks/swiftclient-dsvm-functional-identity-v3-only/post.yaml
    timeout: 6000
    required-projects:
      - openstack/devstack-gate
      - openstack/python-swiftclient
      - openstack/swift

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstack-pypy-jobs-nonvoting
      - lib-forward-testing
      - release-notes-jobs
    check:
      jobs:
        - swift-dsvm-functional
        - swift-dsvm-functional-identity-v3-only:
            voting: false
        - swiftclient-functional
        - swiftclient-functional-identity-v3-only:
            voting: false
        - openstack-tox-py36:
            voting: false
    gate:
      jobs:
        - swift-dsvm-functional
        - swiftclient-functional
    post:
      jobs:
        - openstack-tox-cover
